SET(SRC_SRgbDisplayModule 
${CMAKE_CURRENT_SOURCE_DIR}/src/Modules/SRgbDisplayModule/cpp/SRgbDisplayModule.cpp 
) 
SET(HEADER_SRgbDisplayModule 
${CMAKE_CURRENT_SOURCE_DIR}/src/Modules/SRgbDisplayModule/SRgbDisplayModule.h 
) 
SET(FILES_MODULES_SRgbDisplayModule 
${SRC_SRgbDisplayModule} 
${HEADER_SRgbDisplayModule} 
) 
